# coding: utf-8

# flake8: noqa
"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from bw_serve_client.models.collection import Collection
from bw_serve_client.models.field import Field
from bw_serve_client.models.folder import Folder
from bw_serve_client.models.group import Group
from bw_serve_client.models.item_card import ItemCard
from bw_serve_client.models.item_identity import ItemIdentity
from bw_serve_client.models.item_login import ItemLogin
from bw_serve_client.models.item_secure_note import ItemSecureNote
from bw_serve_client.models.item_template import ItemTemplate
from bw_serve_client.models.lockunlock_success import LockunlockSuccess
from bw_serve_client.models.lockunlock_success_data import LockunlockSuccessData
from bw_serve_client.models.send_template import SendTemplate
from bw_serve_client.models.send_text import SendText
from bw_serve_client.models.status import Status
from bw_serve_client.models.status_data import StatusData
from bw_serve_client.models.status_data_template import StatusDataTemplate
from bw_serve_client.models.unlock_post_request import UnlockPostRequest
from bw_serve_client.models.uris import Uris
