# coding: utf-8

"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bw_serve_client.api.attachments_fields_api import AttachmentsFieldsApi  # noqa: E501


class TestAttachmentsFieldsApi(unittest.TestCase):
    """AttachmentsFieldsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AttachmentsFieldsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_attachment_post(self) -> None:
        """Test case for attachment_post

        Attach a file to an existing vault item.  # noqa: E501
        """
        pass

    def test_object_attachment_id_delete(self) -> None:
        """Test case for object_attachment_id_delete

        Delete an attachment.  # noqa: E501
        """
        pass

    def test_object_attachment_id_get(self) -> None:
        """Test case for object_attachment_id_get

        Retrieve an attachment.  # noqa: E501
        """
        pass

    def test_object_exposed_id_get(self) -> None:
        """Test case for object_exposed_id_get

        Retrieve the number of times a password has been exposed for a login item.  # noqa: E501
        """
        pass

    def test_object_notes_id_get(self) -> None:
        """Test case for object_notes_id_get

        Retrieve the notes of an item.  # noqa: E501
        """
        pass

    def test_object_password_id_get(self) -> None:
        """Test case for object_password_id_get

        Retrieve the password of a login item.  # noqa: E501
        """
        pass

    def test_object_totp_id_get(self) -> None:
        """Test case for object_totp_id_get

        Retrieve the TOTP code of a login item.  # noqa: E501
        """
        pass

    def test_object_uri_id_get(self) -> None:
        """Test case for object_uri_id_get

        Retrieve the URI of a login item.  # noqa: E501
        """
        pass

    def test_object_username_id_get(self) -> None:
        """Test case for object_username_id_get

        Retrieve the username of a login item.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
