# coding: utf-8

"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest
import datetime

from bw_serve_client.models.collection import Collection  # noqa: E501


class TestCollection(unittest.TestCase):
    """Collection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Collection:
        """Test Collection
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Collection`
        """
        model = Collection()  # noqa: E501
        if include_optional:
            return Collection(
                external_id = '',
                groups = [
                    bw_serve_client.models.group.group(
                        hide_passwords = True, 
                        id = '', 
                        read_only = True, )
                    ],
                name = '',
                organization_id = ''
            )
        else:
            return Collection(
        )
        """

    def testCollection(self):
        """Test Collection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
