# coding: utf-8

"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bw_serve_client.api.collections_organizations_api import CollectionsOrganizationsApi  # noqa: E501


class TestCollectionsOrganizationsApi(unittest.TestCase):
    """CollectionsOrganizationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionsOrganizationsApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_confirm_org_member_id_post(self) -> None:
        """Test case for confirm_org_member_id_post

        Confirm a member to a specified Organization.  # noqa: E501
        """
        pass

    def test_list_object_collections_get(self) -> None:
        """Test case for list_object_collections_get

        List Collections from all member Organizations.  # noqa: E501
        """
        pass

    def test_list_object_org_collections_get(self) -> None:
        """Test case for list_object_org_collections_get

        List Collections from a specified Organization.  # noqa: E501
        """
        pass

    def test_list_object_org_members_get(self) -> None:
        """Test case for list_object_org_members_get

        List members of a specified Organization.  # noqa: E501
        """
        pass

    def test_list_object_organizations_get(self) -> None:
        """Test case for list_object_organizations_get

        List Organizations of which you are a member.  # noqa: E501
        """
        pass

    def test_object_org_collection_id_delete(self) -> None:
        """Test case for object_org_collection_id_delete

        Delete a Collection from a specified Organization.  # noqa: E501
        """
        pass

    def test_object_org_collection_id_get(self) -> None:
        """Test case for object_org_collection_id_get

        Retrieve a Collection from a specified Organization.  # noqa: E501
        """
        pass

    def test_object_org_collection_id_put(self) -> None:
        """Test case for object_org_collection_id_put

        Edit a Collection in a specified Organization.  # noqa: E501
        """
        pass

    def test_object_org_collection_post(self) -> None:
        """Test case for object_org_collection_post

        Create a Collection for a specified Organization.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
