# coding: utf-8

"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from bw_serve_client.api.send_api import SendApi  # noqa: E501


class TestSendApi(unittest.TestCase):
    """SendApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SendApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_list_object_send_get(self) -> None:
        """Test case for list_object_send_get

        Retrieve a list of Sends.  # noqa: E501
        """
        pass

    def test_object_send_id_delete(self) -> None:
        """Test case for object_send_id_delete

        Delete a Send.  # noqa: E501
        """
        pass

    def test_object_send_id_get(self) -> None:
        """Test case for object_send_id_get

        Retrieve a Send.  # noqa: E501
        """
        pass

    def test_object_send_id_put(self) -> None:
        """Test case for object_send_id_put

        Edit a Send.  # noqa: E501
        """
        pass

    def test_object_send_post(self) -> None:
        """Test case for object_send_post

        Create a Send.  # noqa: E501
        """
        pass

    def test_send_id_remove_password_post(self) -> None:
        """Test case for send_id_remove_password_post

        Remove the password from a Send.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
