# coding: utf-8

"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from bw_serve_client.api.lock_unlock_api import LockUnlockApi  # noqa: E501


class TestLockUnlockApi(unittest.TestCase):
    """LockUnlockApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LockUnlockApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_lock_post(self) -> None:
        """Test case for lock_post

        Lock your vault.  # noqa: E501
        """
        pass

    def test_unlock_post(self) -> None:
        """Test case for unlock_post

        Unlock your vault.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
