# coding: utf-8

"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from bw_serve_client.api.miscellaneous_api import MiscellaneousApi  # noqa: E501


class TestMiscellaneousApi(unittest.TestCase):
    """MiscellaneousApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MiscellaneousApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_generate_get(self) -> None:
        """Test case for generate_get

        Generate a password or passphrase.  # noqa: E501
        """
        pass

    def test_object_fingerprint_me_get(self) -> None:
        """Test case for object_fingerprint_me_get

        Retrieve your fingerprint phrase.  # noqa: E501
        """
        pass

    def test_object_template_type_get(self) -> None:
        """Test case for object_template_type_get

        Retrieve a JSON template for any object.  # noqa: E501
        """
        pass

    def test_status_get(self) -> None:
        """Test case for status_get

        Get the status of the Bitwarden CLI.  # noqa: E501
        """
        pass

    def test_sync_post(self) -> None:
        """Test case for sync_post

        Sync your vault.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
