# coding: utf-8

"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import unittest

from bw_serve_client.api.folders_api import FoldersApi  # noqa: E501


class TestFoldersApi(unittest.TestCase):
    """FoldersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FoldersApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_list_object_folders_get(self) -> None:
        """Test case for list_object_folders_get

        Retrieve a list of folders in your vault.  # noqa: E501
        """
        pass

    def test_object_folder_id_delete(self) -> None:
        """Test case for object_folder_id_delete

        Delete a folder from your vault.  # noqa: E501
        """
        pass

    def test_object_folder_id_get(self) -> None:
        """Test case for object_folder_id_get

        Retrieve a folder from your vault.  # noqa: E501
        """
        pass

    def test_object_folder_id_put(self) -> None:
        """Test case for object_folder_id_put

        Edit a folder in your vault.  # noqa: E501
        """
        pass

    def test_object_folder_post(self) -> None:
        """Test case for object_folder_post

        Add a folder to your vault.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
