[tool.poetry]
name = "bw_serve_client"
version = "0.0.2"
description = "Vault Management API"
authors = ["OpenAPI Generator Community <team@openapitools.org>"]
license = "NoLicense"
readme = "README.md"
repository = "https://github.com/harleypig/bw-serve-client"
keywords = ["OpenAPI", "OpenAPI-Generator", "Vault Management API"]
include = ["bw_serve_client/py.typed"]

[tool.poetry.dependencies]
python = "^3.7"

urllib3 = ">= 1.25.3, < 2.1.0"
python-dateutil = ">= 2.5.3"
pydantic = "^1.10.5, <2"
aenum = ">=3.1.11"

[tool.poetry.dev-dependencies]
[tool.poetry.group.dev.dependencies]
poetry = "^1.1.4"
pytest = ">=7.2.1"
pytest-cov = ">=2.8.1"
pytest-randomly = ">=3.12.0"
tox = ">=3.9.0"
flake8 = ">=4.0.0"
yapf = "*"

[tool.poetry.group.docs.dependencies]
sphinx = "*"
mkdocs = "*"
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"
