[tool.poetry]
name = "bw_serve_client"
version = "0.0.5"
description = "Bitwarden CLI Vault Management API"
authors = ["OpenAPI Generator Community <team@openapitools.org>"]
license = "NoLicense"
readme = "README.md"
repository = "https://github.com/harleypig/bw-serve-client"
keywords = ['Vault Management API', 'vaultwarden', 'bitwarden']
#include = ["bw_serve_client/py.typed"]

[tool.poetry.dependencies]
aenum = ">=3.1.11"
pydantic = "^2.0.0"
python = "^3.9"
python-dateutil = ">= 2.5.3"
urllib3 = ">= 1.25.3, < 2.1.0"

[tool.poetry.group.dev.dependencies]
flake8 = ">=4.0.0"
mypy = "^1.9.0"
pytest = ">=7.2.1"
pytest-cov = ">=2.8.1"
pytest-mock = "^3.12.0"
pytest-randomly = ">=3.12.0"
tox = ">=3.9.0"
yapf = "^0.40.2"
lxml = "^5.1.0"

[tool.poetry.group.docs.dependencies]
mkdocs = "^1.5.3"
sphinx = "^7.2.6"
sphinx-autodoc-typehints = "^2.0.0"
sphinxcontrib-email = "^0.3.6"
sphinxcontrib-openapi = "^0.8.4"
sphinx-lint = "^0.9.1"

[tool.mypy]
html_report = ".openapi/mypy-reports"
#files = ["bw_serve_client"]
#package = "bw_serve_client"
ignore_missing_imports = true
#follow_imports = "skip"
#namespace_packages = true
#explicit_package_bases = true
check_untyped_defs = false

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.yapf]
# Use PEP8 style as the base
based_on_style = "pep8"

# Basic formatting
indent_width = 2
column_limit = 79
continuation_indent_width = 2

# Whitespace and docstring settings
allow_multiline_dictionary_keys = true
allow_multiline_lambdas = true
blank_line_before_class_docstring = true
blank_line_before_module_docstring = true
indent_dictionary_value = true
spaces_before_comment = [5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75]

# Bracket handling
coalesce_brackets = true
dedent_closing_brackets = true
align_closing_bracket_with_visual_indent = false
split_before_closing_bracket = true

# Line splitting behavior
split_before_arithmetic_operator = true
split_before_dict_set_generator = true
split_before_first_argument = true
split_before_named_assigns = true
split_before_expression_after_opening_paren = false
split_penalty_after_opening_bracket = 0
split_penalty_after_unary_operator = 10000
split_penalty_for_added_line_split = 30
split_penalty_excess_character = 7000

