#!/bin/bash

npm install @openapitools/openapi-generator-cli 

# Nope. Can't figure out how to use from command line.
#npm install api-diff-viewer

# https://pb33f.io/openapi-changes/
npm install @pb33f/openapi-changes
