# coding: utf-8

# flake8: noqa

"""
    Vault Management API

    This schema documents the endpoints available to the Vault Management API, accessible from the Bitwarden CLI using the `bw serve` command ([learn more](https://bitwarden.com/help/cli/)). If you're looking for the **Organization Management** API, refer instead to [this document](https://bitwarden.com/help/api/).

    The version of the OpenAPI document: latest
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

__version__ = "0.0.3"

# import apis into sdk package
from bw_serve_client.api.attachments_fields_api import AttachmentsFieldsApi
from bw_serve_client.api.collections_organizations_api import CollectionsOrganizationsApi
from bw_serve_client.api.folders_api import FoldersApi
from bw_serve_client.api.lock_unlock_api import LockUnlockApi
from bw_serve_client.api.miscellaneous_api import MiscellaneousApi
from bw_serve_client.api.send_api import SendApi
from bw_serve_client.api.vault_items_api import VaultItemsApi

# import ApiClient
from bw_serve_client.api_response import ApiResponse
from bw_serve_client.api_client import ApiClient
from bw_serve_client.configuration import Configuration
from bw_serve_client.exceptions import OpenApiException
from bw_serve_client.exceptions import ApiTypeError
from bw_serve_client.exceptions import ApiValueError
from bw_serve_client.exceptions import ApiKeyError
from bw_serve_client.exceptions import ApiAttributeError
from bw_serve_client.exceptions import ApiException

# import models into sdk package
from bw_serve_client.models.collection import Collection
from bw_serve_client.models.field import Field
from bw_serve_client.models.folder import Folder
from bw_serve_client.models.group import Group
from bw_serve_client.models.item_card import ItemCard
from bw_serve_client.models.item_identity import ItemIdentity
from bw_serve_client.models.item_login import ItemLogin
from bw_serve_client.models.item_secure_note import ItemSecureNote
from bw_serve_client.models.item_template import ItemTemplate
from bw_serve_client.models.lockunlock_success import LockunlockSuccess
from bw_serve_client.models.lockunlock_success_data import LockunlockSuccessData
from bw_serve_client.models.send_template import SendTemplate
from bw_serve_client.models.send_text import SendText
from bw_serve_client.models.status import Status
from bw_serve_client.models.status_data import StatusData
from bw_serve_client.models.status_data_template import StatusDataTemplate
from bw_serve_client.models.unlock_post_request import UnlockPostRequest
from bw_serve_client.models.uris import Uris
